version: '3.7'
services:
    kratos-migrate:
        depends_on: 
            - postgresql-db
        image: oryd/kratos:latest
        container_name: app-kratos-migrate
        environment: 
            - DSN=postgres://${DB_USER}:${DB_PASSWORD}@postgresql-db:${DB_PORT}/${DB_NAME}?sslmode=disable
        command: 
            -c /etc/config/kratos/config.yaml migrate sql -e --yes
        volumes: 
            - ./config:/etc/config/kratos
        restart: on-failure
        networks: 
            - go-network

    kratos:
        depends_on: 
            - kratos-migrate
        image: oryd/kratos:latest
        container_name: app-kratos
        environment: 
            - DSN=postgres://${DB_USER}:${DB_PASSWORD}@postgresql-db:${DB_PORT}/${DB_NAME}?sslmode=disable
        command: 
            serve -c /etc/config/kratos/config.yaml --dev
        volumes: 
            - ./config:/etc/config/kratos
        ports: 
            - '4433:4433'
            - '4434:4434'
        restart: unless-stopped
        networks: 
            - go-network

    postgresql-db:
        image: postgres:latest
        container_name: app-kratos-db
        environment: 
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
            - DATABASE_HOST=${DB_HOST}
        networks: 
            - go-network
        ports: 
            - '${DB_PORT}:${DB_PORT}'
    
    mailslurper:
        depends_on: 
            - postgresql-db
        image: oryd/mailslurper:latest-smtps
        container_name: app-mailslurper
        ports:
            - "4436:4436"
            - "4437:4437"
        networks: 
            - go-network

networks: 
    go-network:
        driver: bridge
    